services:

  zipkin:
    image: openzipkin/zipkin
    container_name: foodcore-zipkin
    ports:
      - "${ZIPKIN_PORT}:${ZIPKIN_PORT}"
    networks:
      - fastfood-network
    restart: unless-stopped
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: foodcore-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - fastfood-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    env_file:
      - .env

networks:
  fastfood-network:
    driver: bridge

volumes:
  prometheus_data: