apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "grafana.fullname" . }}-ingress
  namespace: {{ .Values.namespace.monitor.name }}
  labels:
    app: {{ include "grafana.name" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/health-probe-path: {{ .Values.grafana.ingress.path }}
    appgw.ingress.kubernetes.io/health-probe-port: {{ .Values.grafana.ports.port }}

spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}

  rules:
  - host: {{ (index .Values.ingress.hosts 0).host | quote }}
    http:
      paths:
      - path: {{ .Values.grafana.ingress.path }}
        pathType: {{ .Values.grafana.ingress.pathType }}
        backend:
          service:
            name: {{ include "grafana.fullname" . }}-service
            port: 
              number: {{ .Values.grafana.ports.port }}