name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  TF_VAR_foodcore-backend-resource-group: ${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}
  TF_VAR_foodcore-backend-storage-account: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}
  TF_VAR_foodcore-backend-container: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}
  TF_VAR_foodcore-backend-infra-key: ${{secrets.FOODCORE_INFRA_BACKEND_AZURE_KEY}}

  TF_VAR_chart_name: "foodcore-observability"
  TF_VAR_chart_version: "0.1.${{ github.run_number }}"

jobs:
  infra-info:
    runs-on: ubuntu-latest
    outputs:
      acr_login_server: ${{ steps.acr.outputs.acr_login_server }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      # Somente para que o output seja criado
      - name: Terraform Apply Refresh Only
        working-directory: terraform
        run: terraform apply --refresh-only --auto-approve

      - name: Get ACR Login Server from remote state
        id: acr
        working-directory: terraform
        run: echo "acr_login_server=$(terraform output -raw acr_login_server_from_remote)" >> $GITHUB_OUTPUT

  push:
    needs: infra-info
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Helm Login to ACR
        run: |
          az account set --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
          
          ACR_LOGIN_SERVER=${{ needs.infra-info.outputs.acr_login_server }}
          ACR_USERNAME=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "passwords[0].value" -o tsv)
          echo $ACR_PASSWORD | helm registry login $ACR_LOGIN_SERVER --username $ACR_USERNAME --password-stdin

      - name: Build and Push Package Helm Chart
        run: |
          CHART_VERSION="0.1.${{ github.run_number }}"
          sed -i "s/^version:.*/version: $CHART_VERSION/" kubernetes/foodcore-observability/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: $CHART_VERSION/" kubernetes/foodcore-observability/Chart.yaml
          helm dependency update kubernetes/foodcore-observability
          helm package kubernetes/foodcore-observability -d ./charts
          ACR_NAME=${{ needs.infra-info.outputs.acr_login_server }}
          helm push ./charts/foodcore-observability-*.tgz oci://$ACR_NAME/helm

  terraform:
    runs-on: ubuntu-latest
    needs: [push, infra-info]

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="subscription_id=${{secrets.AZURE_SUBSCRIPTION_ID}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan